name: bnotes
description: Note taking application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  uuid: ^3.0.4
  path_provider: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/bnotes.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/bnotes.png
    - images/google.png

  fonts:
    - family:  outline_material_icons
      fonts:
        - asset: res/outline_material_icons.ttf